// Generated by CoffeeScript 1.6.3
var originSprite,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

originSprite = (function() {
  function originSprite(sprite) {
    var _this = this;
    this.sprite = sprite;
    this.removeObject = __bind(this.removeObject, this);
    this.addSprite = __bind(this.addSprite, this);
    this.childlist = [];
    this.sprite.addEventListener('touchstart', function(e) {
      if (typeof _this.touchesBegan === 'function') {
        return _this.touchesBegan(e);
      }
    });
    this.sprite.addEventListener('touchmove', function(e) {
      if (typeof _this.touchesMoved === 'function') {
        return _this.touchesMoved(e);
      }
    });
    this.sprite.addEventListener('touchend', function(e) {
      if (typeof _this.touchesEnded === 'function') {
        return _this.touchesEnded(e);
      }
    });
    this.sprite.addEventListener('touchcancel', function(e) {
      if (typeof _this.touchesCanceled === 'function') {
        return _this.touchesCanceled(e);
      }
    });
  }

  originSprite.prototype.addSprite = function(sprite) {
    this.childlist.push(sprite);
    return core.rootScene.addChild(sprite);
  };

  originSprite.prototype.removeObject = function(obj) {
    var s, _i, _len, _ref;
    _ref = obj.childlist;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      s = _ref[_i];
      core.rootScene.removeChild(s);
    }
    obj.sprite.active = false;
    obj.sprite.visible = false;
    obj.sprite.seedobj = null;
    obj.sprite.removeEventListener('enterframe');
    return obj.sprite.characterObj = null;
  };

  return originSprite;

})();
