// Generated by CoffeeScript 1.3.3
var originSprite,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

originSprite = (function() {

  function originSprite(sprite) {
    var _this = this;
    this.sprite = sprite;
    this.addSprite = __bind(this.addSprite, this);

    this.childlist = [];
    this.sprite.addEventListener('touchstart', function(e) {
      if (typeof _this.touchesBegan === 'function') {
        return _this.touchesBegan(e);
      }
    });
    this.sprite.addEventListener('touchmove', function(e) {
      if (typeof _this.touchesMoved === 'function') {
        return _this.touchesMoved(e);
      }
    });
    this.sprite.addEventListener('touchend', function(e) {
      if (typeof _this.touchesEnded === 'function') {
        return _this.touchesEnded(e);
      }
    });
    this.sprite.addEventListener('touchcancel', function(e) {
      if (typeof _this.touchesCanceled === 'function') {
        return _this.touchesCanceled(e);
      }
    });
  }

  originSprite.prototype.addSprite = function(sprite) {
    this.childlist.push(sprite);
    return core.rootScene.addChild(sprite);
  };

  return originSprite;

})();
