// Generated by CoffeeScript 1.3.3
var _stationary;

_stationary = (function() {

  function _stationary(sprite) {
    var _this = this;
    this.sprite = sprite;
    if ((this.sprite != null)) {
      this.sprite.addEventListener('touchstart', function(e) {
        if (typeof _this.touchesBegan === 'function') {
          return _this.touchesBegan(e);
        }
      });
      this.sprite.addEventListener('touchmove', function(e) {
        if (typeof _this.touchesMoved === 'function') {
          return _this.touchesMoved(e);
        }
      });
      this.sprite.addEventListener('touchend', function(e) {
        if (typeof _this.touchesEnded === 'function') {
          return _this.touchesEnded(e);
        }
      });
      this.sprite.addEventListener('touchcancel', function(e) {
        if (typeof _this.touchesCanceled === 'function') {
          return _this.touchesCanceled(e);
        }
      });
    }
  }

  _stationary.prototype.destructor = function() {};

  _stationary.prototype.behavior = function() {};

  _stationary.prototype.touchesBegan = function(e) {};

  _stationary.prototype.touchesMoved = function(e) {};

  _stationary.prototype.touchesEnded = function(e) {};

  _stationary.prototype.touchesCanceled = function(e) {};

  return _stationary;

})();
