// Generated by CoffeeScript 1.3.3
var bear,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

bear = (function(_super) {

  __extends(bear, _super);

  function bear(sprite) {
    bear.__super__.constructor.call(this, sprite);
    JSLog("bear const");
    this.sprite.tl.fadeOut(20).fadeIn(20).loop();
  }

  bear.prototype.behavior = function() {
    return bear.__super__.behavior.call(this);
  };

  bear.prototype.touchesBegan = function(e) {
    bear.__super__.touchesBegan.call(this, e);
    return JSlog("bear_x=%@", e.x);
  };

  bear.prototype.touchesMoved = function(e) {
    return bear.__super__.touchesMoved.call(this, e);
  };

  bear.prototype.touchesEnded = function(e) {
    return bear.__super__.touchesEnded.call(this, e);
  };

  bear.prototype.touchesCanceled = function(e) {
    return bear.__super__.touchesCanceled.call(this, e);
  };

  return bear;

})(_stationary);
