// Generated by CoffeeScript 1.3.3
var enchantMain;

enchantMain = (function() {

  function enchantMain() {
    var bear;
    bear = createObject(SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2, 0, 0, 0, 0, 32, 32, 1.0, stationary, ANIMLIST, 0, true);
  }

  return enchantMain;

})();
