// Generated by CoffeeScript 1.3.3
var enchantMain;

enchantMain = (function() {

  function enchantMain() {
    var obj;
    obj = addObject(rand(240), 32, rand(10) - 5, 0, 0.5, 0, 32, 32, 0, 100, stationary, [0, 1, 2, 1], true);
  }

  return enchantMain;

})();
