// Generated by CoffeeScript 1.3.3
var stationary;

stationary = (function() {

  function stationary(obj) {
    this.obj = obj;
  }

  stationary.prototype.behavior = function() {
    if (this.obj.x < -16 || this.obj.x > SCREEN_WIDTH - 16) {
      this.obj.xs *= -1;
    }
    if (this.obj.y > SCREEN_HEIGHT - 32) {
      this.obj.ys *= -1;
      return this.obj.y = SCREEN_HEIGHT - 32;
    }
  };

  return stationary;

})();
